# Generated by Django 5.1.3 on 2025-05-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
