# Generated by Django 5.1.3 on 2025-05-04 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="expiration_date",
            field=models.DateField(default=datetime.date(2025, 5, 4)),
            preserve_default=False,
        ),
    ]
